name = "YA(N)A"
author = "Qiinr"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "acd0fe9e33ce0d81de705bef7b9624067a32f8d9dc19fa8a4e33faa79ca3b02c"

[versions]
fabric = "0.17.3"
minecraft = "1.20.1"

[options]
no-internal-hashes = false
