name = "YA(N)A"
author = "Qiinr"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "942c2b3f1954d268f06109a3e1133566bdbd99c8f4416fdd148ab236d6d0a9c8"

[versions]
fabric = "0.17.3"
minecraft = "1.20.1"

[options]
no-internal-hashes = false
